#									JaTeste! 							#
#																		#
# 						Special Makefile for running tests 				#
#																		#
#########################################################################

define parser-test-passing =
@echo "Testing '$^'";
@if [ '$(shell ./jateste.native < $^ | grep 'Successfully parsed')' = 'Successfully parsed' ] ; then \
    echo " \033[0;32m ---->  \033[0mTest passed!"; \
else \
    echo " \033[0;31m ---->  \e[0mTest did not pass, something broke!"; \
    exit 1; \
fi
endef

# Run parser tests
test-parser: test-parser-basic test-parser-full

test-parser-basic: ../test/parsing_tests/basic_test.jt
	$(parser-test-passing)

test-parser-full: ../test/parsing_tests/full_test.jt
	$(parser-test-passing)
